let a = 20;

console.log(a>10);
console.log(a>=10);
console.log(a<10);
console.log(a<=10);

console.log (a==10);
console.log (a!=10); //dl "!" hace referencia a decir que dime si a es diferente a 10
console.log (a!="10"); // aqui es lo mismo pero nos va dar un false ya que el 10 esta como un string o texto




// estos son los que se deben utilizar para identificar si es igaul el tipo y tambien el valor del dato
console.log (a===20);
console.log (a!==10);