console.log (true && true);
console.log (false && true); // el and en javascript se identifica con el simbolo & imprimido dos veces


let mayor = false;
let suscrito = true;

console.log ("operador and", mayor&&suscrito);
console.log ("operador or", mayor||suscrito);
console.log ("operador not", !suscrito);

let catalogoinfantil = !mayor;
console.log ("acceso a catalogo infantil", catalogoinfantil);